### ISSUE TITLE
Dashboard is not encrypted

### ISSUE THREAD

**Issue by isaak42** [astarte-platform/astarte-kubernetes-operator#255]
I deployed Astarte recently, and when I navigate to `dashboard.astarte.<mydomain>.com`, the dashboard login page shows up, but without any encryption. I am using the `astarte-operator-1.0.2` helm chart, and my app version is `1.0.1`.

I am using the new AstarteDefaultIngress.
Here is my ingress file:
```
apiVersion: ingress.astarte-platform.org/v1alpha1
kind: AstarteDefaultIngress
metadata:
  name: adi
  namespace: astarte
spec:
  ### Astarte Default Ingress CRD
  astarte: astarte
  tlsSecret: astarte-tls-cert
  api:
    exposeHousekeeping: true
  dashboard:
    deploy: true
    ssl: true
    host: dashboard.astarte.<my_domain>.com
  broker:
    deploy: true
    serviceType: LoadBalancer
    # loadBalancerIP is needed if your certificate is obtained with the solution of the HTTP
    # challenge, othewise it's optional. Please, be aware that the possibilities and modes for
    # assigning a loadBalancerIP to a service depend on your cloud provider.
    loadBalancerIP: <my_ip>
```

Additionally, I have a secret in the `astarte` namespace of type `kubernetes.io/tls` called `astarte-tls-cert`. 
When I run `kubectl describe ingress adi -n astarte`, I get the following output:

```
Name:             adi-api-ingress
Namespace:        astarte
Address:          <my_ip>
Default backend:  default-http-backend:80 (10.8.1.3:8080)
TLS:
  astarte-tls-cert terminates api.astarte.<my_domain>.com
  astarte-tls-cert terminates dashboard.astarte.<my_domain>.com
Rules:
  Host                                Path  Backends
  ----                                ----  --------
  api.astarte.<my_domain>.com
                                      /appengine(/|$)(.*)   astarte-appengine-api:http (10.8.2.36:4000)
  api.astarte.<my_domain>.com
                                      /pairing(/|$)(.*)   astarte-pairing-api:http (10.8.0.22:4000)
  api.astarte.<my_domain>.com
                                      /realmmanagement(/|$)(.*)   astarte-realm-management-api:http (10.8.0.20:4000)
  api.astarte.<my_domain>.com
                                      /housekeeping(/|$)(.*)   astarte-housekeeping-api:http (10.8.0.19:4000)
  dashboard.astarte.<my_domain>.com
                                      /()(.*)   astarte-dashboard:http (10.8.0.25:80)
Annotations:                          nginx.ingress.kubernetes.io/configuration-snippet:
                                        more_set_headers "X-Frame-Options: SAMEORIGIN";
                                        more_set_headers "X-XSS-Protection: 1; mode=block";
                                        more_set_headers "X-Content-Type-Options: nosniff";
                                        more_set_headers "Referrer-Policy: no-referrer-when-downgrade";
                                      nginx.ingress.kubernetes.io/rewrite-target: /$2
                                      nginx.ingress.kubernetes.io/server-snippet:
                                        location ~* "/(appengine|flow|housekeeping|pairing|realmmanagement)/metrics" {
                                          deny all;
                                          return 404;
                                        }
                                      nginx.ingress.kubernetes.io/ssl-redirect: false
                                      nginx.ingress.kubernetes.io/use-regex: true
Events:                               <none>
```
Any idea what might be going on?
