### ISSUE TITLE
App name for replicated Data Updater Plant should not have index suffix

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte-kubernetes-operator#259]
Currently Data Updater Plant replicas generate `metadata` similar to this:
```
  labels:
    app: astarte-data-updater-plant-1
    astarte-component: data-updater-plant
    astarte-instance-name: astarte
    component: astarte
```
but `app` should be `astarte-data-updater-plant` instead (see, e.g., `vernemq`, which does the correct thing).
