### ISSUE TITLE
 AWS Keyspaces with Astarte Kubernetes Operator

### ISSUE THREAD

**Issue by lirei-user** [astarte-platform/astarte-kubernetes-operator#351]
Hello Astarte Team,

I'm facing challenges integrating AWS Keyspaces with Astarte Kubernetes Operator, specifically with SSL certificate mounting. Despite creating a Kubernetes secret for the certificate obtained via `curl https://certs.secureserver.net/repository/sf-class2-root.crt -O`, the containers can't connect to the database. The YAML configuration used is:

```yaml
cassandra:
  deploy: false
  nodes: "cassandra.us-east-1.amazonaws.com:9142"
  connection:
    autodiscovery: false
    username: myprivateusername
    password: myprivatepassword
    sslConfiguration:
      enabled: true
      customCASecret: 
        name: aws-cassandra-cert
```
Additionally, it's worth noting that the connection to AWS Keyspaces works well when using `cqlsh`. This indicates that the basic configuration and credentials are correct. However, the issue seems to arise specifically when attempting to integrate this setup with the Astarte Kubernetes Operator, particularly concerning the mounting and use of the SSL certificate.

Guidance on proper certificate mounting and configuration for AWS Keyspaces would be greatly appreciated.

Best,
