### ISSUE TITLE
CRD (v1alpha3): schema for connections to RabbitMQ and Cassandra/Scylla should be uniform

### ISSUE THREAD

**Issue by matt-mazzucato** [astarte-platform/astarte-kubernetes-operator#367]
The v1alpha2 version of the Astarte resource handles the config for connections in the following manner:
* for Cassandra/Scylla:
  ```yaml
  cassandra:
    nodes: <host:port[,host:port...]>
  ```
* for RabbitMQ:
  ```yaml
  rabbitmq:
    connection:
      host: <host>
      port: <port>
  ```
The new API version (i.e. v1alpha3) should be updated to expose a uniform interface when configuring connections. The following is proposed:
```yaml
<component-name>:
  connection:
    nodes:
    - host: <host>
      port: <port>
```

The conversion between v1alpha2 and v1alpha3 must be updated accordingly.
