### ISSUE TITLE
Feature Request: Support for Configurable Liveness and Readiness Probes in Astarte Custom Resources (CRs)

### ISSUE THREAD

**Issue by jingwenzz** [astarte-platform/astarte-kubernetes-operator#387]
**Description**  It would be highly beneficial to have the ability to configure `livenessProbe` and `readinessProbe` settings directly within the Astarte Custom Resource (CR). Currently, these settings are managed internally by the operator, with no option for customization. This limitation can lead to challenges in tailoring health check configurations to suit specific deployment environments and workloads.

**Use Case** Customizing probes can:
- Allow fine-tuning of `initialDelaySeconds`, `timeoutSeconds`, `failureThreshold`, etc., for components running in diverse infrastructure conditions.
- Help avoid false positives or unnecessary restarts in environments with slower response times or transient load spikes.
- Improve observability and operational control by aligning health checks with application-specific requirements.

**Proposed Solution** Introduce support for customizable `livenessProbe` and `readinessProbe` settings in the Astarte CR. This could be implemented as optional fields in the CR for each Astarte component (e.g., `appengineApi`, `housekeepingApi`, etc.).

Example:
```
components:
  appengineApi:
    livenessProbe:
      httpGet:
        path: /health
        port: 4000
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 20
      timeoutSeconds: 10
      failureThreshold: 5
    readinessProbe:
      httpGet:
        path: /health
        port: 4000
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 20
      timeoutSeconds: 10
      failureThreshold: 5
```

**Impact This feature would:**
Provide greater flexibility in managing health checks for Astarte deployments.
Reduce operator intervention by eliminating the need to manually patch deployments post-deployment.
Improve the stability and reliability of Astarte clusters in diverse environments.
Additional Context This request aligns with best practices for Kubernetes deployments, where configurable probes are commonly used to adapt applications to their specific operational contexts.

Thank you for considering this feature request. Please let me know if any additional details or use cases are required.
