### ISSUE TITLE
VerneMQ is failing to start

### ISSUE THREAD

**Issue by IvaskevychYuriy** [astarte-platform/astarte-kubernetes-operator#388]
Hello, I have an issue running Astarte operator as the VerneMQ pod is continuously crashing.

## Setup

Infra:
- K3S on WSL2: Client Version: v1.31.0; Server Version: v1.30.4+k3s1
- Helm 3

Existing components:
- `cert-manager` version 1.16.1
- `bitnami/cassandra` version 12.0.4
- `bitnami/rabbitmq` version 14.0.0

For reference, here are values overrides for cassandra chart:
```yaml
dbUser:
  user: test
  password: test
  forcePassword: true
 
cluster:
  name: cassandra
  seedCount: 1
  numTokens: 256
  datacenter: dc1
  rack: rack1
  endpointSnitch: SimpleSnitch
```

And for rabbitmq:
```yaml
auth:
  username: test
  password: test
  erlangCookie: test
```

Install Astarte operator via
```
helm upgrade -i astarte-operator astarte/astarte-operator --version 24.5.0
```
Install certificate by applying (note, I already have `root-ca` ClusterIssuer):
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls2
  namespace: default
spec:
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  isCA: false
  usages:
    - server auth
    - client auth
  commonName: Astarte
  dnsNames:
    - astarte-broker.local.coom
  secretName: tls2
  issuerRef:
    name: root-ca
    kind: ClusterIssuer
```

Install Astarte CR and point to existing Cassandra and RabbitMQ instances:
```yaml
apiVersion: api.astarte-platform.org/v1alpha3
kind: Astarte
metadata:
  name: astarte
  namespace: default
spec:
  version: 1.2.0
  api:
    host: astarte-api.local.com
  cassandra:
    deploy: false
    nodes: cassandra:9042
    connection:
      username: test
      password: test
  cfssl:
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 20m
        memory: 128Mi
    storage:
      size: 1Gi
  rabbitmq:
    deploy: false
    connection:
      host: astarte-broker-rabbitmq
      username: test
      password: test
      port: 5672
      virtualHost: /
  vernemq:
    host: astarte-broker.local.com
    sslListener: true
    sslListenerCertSecretName: tls2
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
```

## Issue
Eventually all the pods run fine **except** the VerneMQ one:
![image](https://github.com/user-attachments/assets/4f3c9c7d-de61-41ed-80b2-ae200db741e7)

Logs reveal the following:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 31820    0 31820    0     0  1942k      0 --:--:-- --:--:-- --:--:-- 1942k
/opt/vernemq/bin/vernemq.sh: line 29: warning: command substitution: ignored null byte in input
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 31820    0 31820    0     0   327k      0 --:--:-- --:--:-- --:--:--  323k
Error generating config with cuttlefish
  run `vernemq config generate -l debug` for more information.
/opt/vernemq/bin/vernemq.sh: line 179: ps: command not found
```

Describe shows the following version of the container (if this helps)
```
    Container ID:  docker://4092584bd2ffb412ca6994c21d5338d56ad9c24bab67bcea98b1845dab67247e
    Image:         astarte/vernemq:1.2.0
```

## What I've tried
The error seems originating from [here](https://github.com/astarte-platform/astarte_vmq_plugin/blob/master/docker/bin/vernemq.sh#L179)

So I've edited statefulset to keep the pod in sleep, exec into it and installed the stuff using `apt-get update && apt-get install -y procps`
Then ran `/opt/vernemq/bin/vernemq.sh` manually and got the same error but this time without the last line (about command not found)

I've also tried reinstalling it along with the operator, deleting the volume - still the same.

Any ideas?
