### ISSUE TITLE
VerneMQ there is no mqtts listener after deploying

### ISSUE THREAD

**Issue by smietanka** [astarte-platform/astarte-kubernetes-operator#400]
Hello, I am facing an issue with an Astarte Operator while deploying VerneMQ.

## Some details about infrastructure:

- k3s on WSL2 version v1.29.6+k3s2 (b4b156d9)
- Helm 3
- cert-manager exists
- cassandra

Generally all APIs after deploying are working
![image](https://github.com/user-attachments/assets/f7cc481e-a03e-4eb5-8b62-de778648dde7)

## Astarte Operator details
Astare Operator image tag used: `24.5.1`

## My Astarte Cluster deploying
`templates/astarte.yaml`
```
apiVersion: api.astarte-platform.org/v1alpha2
kind: Astarte
metadata:
  name: {{ .Values.name }}
spec:
  version: {{ .Values.version }}
  api:
    host: {{ .Values.dnsNames.api }}
  rabbitmq:
    deploy: false
    {{- with .Values.rabbitmq.connection }}
    connection:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  cassandra:
    deploy: false
    nodes: {{ .Values.cassandra.nodes | quote }}
    {{- with .Values.cassandra.connection }}
    connection:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  vernemq:
    host: {{ .Values.dnsNames.broker }}
    sslListener: {{ .Values.vernemq.sslEnabled }}
    sslListenerCertSecretName: {{ .Values.cert.name }}
    {{- with .Values.vernemq.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  cfssl:
    {{- with .Values.cfssl.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.cfssl.storage }}
    storage:
      {{- toYaml . | nindent 6 }}
    {{- end }}
```

`values.yamls`
```
name: astarte
version: 1.2.0

dnsNames:
  api: "astarte-api.local.com"
  broker: "astarte-broker.local.com"
  dashboard: "astarte-dashboard.local.com"

cert:
  clusterIssuer: root-ca
  name: astarte-tls

rabbitmq:
  connection:
    host: astarte-broker-rabbitmq
    port: 5672
    username: user
    password: user
    virtualHost: "/"

cassandra:
  nodes: cassandra:9042
  connection:
    username: user
    password: user

vernemq:
  sslEnabled: true
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

cfssl:
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 128Mi
  storage:
    size: 1Gi

```
Not included, because I think its not needed: 
- `templates/certs.yaml` - include generating astarte-tls certificate 
- `templates/ingress.yaml` - include haproxy coraza rules for all apis, broker, dashboard 

### VerneMQ details:
There is no 8883 port visible on service.
`kubectl get svc --field-selector metadata.name=astarte-vernemq`
```
NAME              TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                      AGE
astarte-vernemq   ClusterIP   None         <none>        1883/TCP,1885/TCP,8888/TCP   4m5s
```

`kubectl logs astarte-vernemq-0`
```
config is OK
-config /opt/vernemq/data/generated.configs/app.2025.01.14.15.57.50.config -args_file /opt/vernemq/bin/../etc/vm.args -vm_args /opt/vernemq/bin/../etc/vm.args
Exec:  /opt/vernemq/bin/../erts-14.1/bin/erlexec -boot /opt/vernemq/bin/../releases/1.13.0+build.25.ref1cc57fa6/vernemq               -config /opt/vernemq/data/generated.configs/app.2025.01.14.15.57.50.config -args_file /opt/vernemq/bin/../etc/vm.args -vm_args /opt/vernemq/bin/../etc/vm.args              -pa /opt/vernemq/bin/../lib/erlio-patches -- console -noshell -noinput
Root: /opt/vernemq/bin/..
Loaded NodeClock fromDisk #{{'VerneMQ@astarte-vernemq-0.astarte-vernemq.default.svc.cluster.local',
                                <<8,53,14,46,32,10,195,229,90,147,53,88,58,
                                  23,16,153,138,93,148,196>>} =>
                                {0,0}}
Loaded NodeClock fromDisk #{{'VerneMQ@astarte-vernemq-0.astarte-vernemq.default.svc.cluster.local',
                                <<8,53,14,46,32,10,195,229,90,147,53,88,58,
                                  23,16,153,138,93,148,196>>} =>
                                {0,0}}
Loaded NodeClock fromDisk #{{'VerneMQ@astarte-vernemq-0.astarte-vernemq.default.svc.cluster.local',
                                <<8,53,14,46,32,10,195,229,90,147,53,88,58,
                                  23,16,153,138,93,148,196>>} =>
                                {0,0}}
Loaded NodeClock fromDisk #{{'VerneMQ@astarte-vernemq-0.astarte-vernemq.default.svc.cluster.local',
                                <<8,53,14,46,32,10,195,229,90,147,53,88,58,
                                  23,16,153,138,93,148,196>>} =>
                                {1,0}}
Loaded NodeClock fromDisk #{{'VerneMQ@astarte-vernemq-0.astarte-vernemq.default.svc.cluster.local',
                                <<8,53,14,46,32,10,195,229,90,147,53,88,58,
                                  23,16,153,138,93,148,196>>} =>
                                {0,0}}
Loaded NodeClock fromDisk #{{'VerneMQ@astarte-vernemq-0.astarte-vernemq.default.svc.cluster.local',
                                <<8,53,14,46,32,10,195,229,90,147,53,88,58,
                                  23,16,153,138,93,148,196>>} =>
                                {0,0}}
Loaded NodeClock fromDisk #{{'VerneMQ@astarte-vernemq-0.astarte-vernemq.default.svc.cluster.local',
                                <<8,53,14,46,32,10,195,229,90,147,53,88,58,
                                  23,16,153,138,93,148,196>>} =>
                                {0,0}}
Loaded NodeClock fromDisk #{{'VerneMQ@astarte-vernemq-0.astarte-vernemq.default.svc.cluster.local',
                                <<8,53,14,46,32,10,195,229,90,147,53,88,58,
                                  23,16,153,138,93,148,196>>} =>
                                {0,0}}
Loaded NodeClock fromDisk #{{'VerneMQ@astarte-vernemq-0.astarte-vernemq.default.svc.cluster.local',
                                <<8,53,14,46,32,10,195,229,90,147,53,88,58,
                                  23,16,153,138,93,148,196>>} =>
                                {0,0}}
Loaded NodeClock fromDisk #{{'VerneMQ@astarte-vernemq-0.astarte-vernemq.default.svc.cluster.local',
                                <<8,53,14,46,32,10,195,229,90,147,53,88,58,
                                  23,16,153,138,93,148,196>>} =>
                                {4,0}}

15:57:57.918 [info] Starting Astarte plugin v1.2.0.
```

After investigate `/opt/vernemq/data/generated.configs/app.2025.01.14.15.57.50.config` file (directly from pod) I can see:

```
{listeners,
          [{mqtt,
               [{{{10,42,0,194},1885},
                 [{max_connections,infinity},
                  {max_connection_lifetime,0},
                  {nr_of_acceptors,10},
                  {mountpoint,[]},
                  {proxy_protocol,true},
                  {allowed_protocol_versions,[3,4,5,131]},
                  {allow_anonymous_override,false}]},
                {{{10,42,0,194},1883},
                 [{max_connections,infinity},
                  {max_connection_lifetime,0},
                  {nr_of_acceptors,10},
                  {mountpoint,[]},
                  {proxy_protocol,false},
                  {allowed_protocol_versions,[3,4,5,131]},
                  {allow_anonymous_override,false}]}]},
           {mqtts,[]},
           {mqttws,
               [{{{10,42,0,194},8080},
                 [{max_connections,infinity},
                  {max_connection_lifetime,0},
                  {nr_of_acceptors,10},
                  {mountpoint,[]},
                  {proxy_protocol,false},
                  {proxy_xff_support,false},
                  {proxy_xff_use_cn_as_username,false},
                  {proxy_xff_cn_header,"x-ssl-client-cn"},
                  {allowed_protocol_versions,[3,4,5,131]}]}]},
           {mqttwss,[]},
           {vmq,
               [{{{10,42,0,194},44053},
                 [{max_connections,infinity},
                  {nr_of_acceptors,10},
                  {mountpoint,[]},
                  {high_watermark,8192},
                  {low_watermark,4096},
                  {high_msgq_watermark,8192},
                  {low_msgq_watermark,4096}]}]},
           {vmqs,[]},
           {http,
               [{{{10,42,0,194},8888},
                 [{max_connections,infinity},
                  {nr_of_acceptors,10},
                  {config_mod,vmq_http_config},
                  {config_fun,config},
                  {max_request_line_length,8000},
                  {http_modules,"[]"},
                  {listener_name,"metrics"},
                  {proxy_protocol,false}]},
                {{{0,0,0,0},8888},
                 [{max_connections,infinity},
                  {nr_of_acceptors,10},
                  {config_mod,vmq_http_config},
                  {config_fun,config},
                  {max_request_line_length,8000},
                  {http_modules,"[]"},
                  {listener_name,"default"},
                  {proxy_protocol,false}]}]},
           {https,[]}]}
```

Do you have any idea why mqtts is not there?

**Comment by smietanka** [comment]
Update: 
Hello again, previously VerneMQ generates config file without mqtts listener. I tried to redeploy everything and by some reason now I can see mqtts listener in the generated config file with proper certificates. (maybe something was not deployed properly, for example cluster issuer).
```
{mqtts,
               [{{{10,42,0,25},8883},
                 [{max_connections,infinity},
                  {max_connection_lifetime,0},
                  {nr_of_acceptors,10},
                  {mountpoint,[]},
                  {cafile,"/opt/vernemq/etc/ca.pem"},
                  {depth,1},
                  {certfile,"/opt/vernemq/etc/cert.pem"},
                  {eccs,
                      [sect571r1,sect571k1,secp521r1,brainpoolP512r1,
                       sect409k1,sect409r1,brainpoolP384r1,secp384r1,
                       sect283k1,sect283r1,brainpoolP256r1,secp256k1,
                       secp256r1]},
                  {keyfile,"/opt/vernemq/etc/privkey.pem"},
                  {require_certificate,true},
                  {tls_version,'tlsv1.2'},
                  {use_identity_as_username,true},
                  {psk_support,false},
                  {pskfile,"./etc/vmq.psk"},
                  {pskfile_separator,":"},
                  {psk_identity_hint,"VMQ_PSK"},
                  {allowed_protocol_versions,[3,4,5,131]},
                  {allow_anonymous_override,false}]}]}
```

Anyway.. some things left for example I still cannot figure out why my astarte-vernemq-0 service doesn't show 8883 port. 
Btw I am trying to connect to the devices using AstarteDeviceSDKExample code written in C# but I am getting
![image](https://github.com/user-attachments/assets/5e2f025c-f326-4d07-b634-3e1652e76bdb)

Also is there way to change tls version to 1.3? I think our load balancer is accepting only tls 1.3 version over 4th transport layer.

**Comment by smietanka** [comment]
Some workaround for me was to reapply `astarte-vernemq` service with specified mqtt-ssl and using node port using this yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: astarte-vernemq
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
  - name: mqtt-reverse
    port: 1885
    protocol: TCP
    targetPort: mqtt-reverse
  - name: webadmin
    port: 8888
    protocol: TCP
    targetPort: webadmin
  - name: mqtt-ssl
    port: 8883
    protocol: TCP
    targetPort: 8883
    nodePort: 31783
  selector:
    app: astarte-vernemq
  sessionAffinity: None
  type: NodePort
```

Only after this I am able to connect to the broker using `31783`. For now it is unblocking me but I should be able to configure it from the charts. Ofc the best thing should be to find reason why it was not worked
