### ISSUE TITLE
api/broker host setup

### ISSUE THREAD

**Issue by shortwavedave** [astarte-platform/astarte-kubernetes-operator#75]
When setting up a cluster using astartectl it asks for an API Host and a Broker Host. In the example in the docs it shows this:

when I'm setting up the cluster, the console asks for an API host:
Please enter the API Host for this Deployment

```
api:
    host: "api.astarte.yourdomain.com" # MANDATORY

vernemq:
    host: "broker.astarte.yourdomain.com"
```

On my local nameserver (this is a deployment on a microk8s cluster), I only have one resolvable domain name, say "yourdomain.com", and I can't add prefixes (as far as I know) such as api.astarte or broker.astarte.

Can I set both hosts to my domain name (e.g., yourdomain.com), or do they need unique names?

Also, I have the voyager operator installed, can I set up the astarte cluster to use a NodePort type ingress instead of load balancer?
