### ISSUE TITLE
tlsRef Specification

### ISSUE THREAD

**Issue by shortwavedave** [astarte-platform/astarte-kubernetes-operator#84]
If you create a self-signed certificate, what needs to be filled out here:

https://github.com/astarte-platform/astarte-kubernetes-operator/blob/b457579b22dd31fc4acf790b3fa00e9a20780190/deploy/crds/api.astarte-platform.org_astartevoyageringresses_crd.yaml#L98

**Comment by shortwavedave** [comment]
Voyager ingress has different keys, so I'm not sure how to match them up:

```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: demo
spec:
  tls:
  - secretName: tls-secret
    hosts:
    - one.example.com
  rules:
  - host: one.example.com
    http:
      paths:
      - backend:
          serviceName: test-service
          servicePort: '80'
```
