### ISSUE TITLE
tutorial on minikube

### ISSUE THREAD

**Issue by shortwavedave** [astarte-platform/astarte-kubernetes-operator#85]
Could someone put together a tutorial using minikube or microk8s? I've been trying to get this working on a local machine for awhile now with no luck. Here are the steps I've taken with minikube:

**minikube commands**
```
minikube config set memory 6442
minikube config set cpus 6
minikube config set vm-driver virtualbox
minikube config set disk-size 80000
minikube start
```

**Voyager install**
```
helm repo add appscode https://charts.appscode.com/stable/
helm repo update
helm search repo appscode/voyager --version v12.0.0-rc.1
helm install voyager-operator appscode/voyager --version v12.0.0-rc.1 --namespace kube-system --set cloudProvider=minikube
```

**Astarte commands**
```
astartectl cluster install-operator
astartectl cluster instances deploy

What Astarte version would you like to install? [0.10.2]
Cluster has 1 nodes
Allocatable CPU is 6000m
Allocatable Memory is 6G

You can safely deploy the following Profiles on this cluster:
burst: Burst profile for test Clusters. No deterministic allocations, all Astarte Pods work on bursts.

Which profile would you like to deploy? burst
Please enter the name for this Astarte instance: [astarte] astarte-pigeo
Please enter the namespace where the Astarte instance will be deployed: [astarte]
Please enter the API Host for this Deployment: myhost.localdom.com/astarte-api
Please enter the MQTT Broker Host for this Deployment: myhost.localdom.com
Please enter the Cassandra Volume size for this Deployment: [10Gi]
Please enter the RabbitMQ Volume size for this Deployment: [4Gi]
Please enter the VerneMQ Volume size for this Deployment: [4Gi]
Please enter the CFSSL Volume size for this Deployment: [2Gi]
Please enter the CFSSL DB Driver for this deployment.
Please note that leaving this empty will default to using SQLite, which is strongly discouraged in production.
CFSSL DB Driver:

Your Astarte instance is ready to be deployed!
Do you wish to review the configuration before deployment? [y/n]: y
```

In this configuration, the housekeeping pod will always crash and restart in a loop. Increasing the pod memory limit helps for a short bit, but eventually the OOM kills it.

Since this is a local configuration, I use a self-signed cert:
`openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out mycert.crt -keyout myscert.key`

**Create a secret in kubernetes**
`kubectl create secret tls tls-secret --namespace=astarte --cert=$PWD/mycert.crt --key=$PWD/mycert.key`

**Ingress Config**
```
apiVersion: api.astarte-platform.org/v1alpha1
kind: AstarteVoyagerIngress
metadata:
  name: my-ingress
  namespace: astarte
spec:
  # The Astarte Instance the Ingress will be attached to
  astarte: astarte-test
  api:
    tlsRef:
      name: "tls-secret"
    tlsSecret: "tls-secret"
    exposeHousekeeping: true
  broker:
    deploy: true
    tlsSecret: "tls-secret"
    tlsRef:
      name: "tls-secret"
  dashboard:
    ssl: true
    tlsSecret: "tls-secret"
    tlsRef:
      name: "tls-secret"
  letsencrypt:
    use: false
    acmeEmail: info@yourdomain.com
    challengeProvider:
      dns:
        provider: digitalocean
        credentialSecretName: voyager-digitalocean
```

All the endpoints throw a 

> 503 Service error "No server is available to handle this request"

So I think there is a problem with the ingress configuration, but I don't know where. I would be happy to contribute this tutorial to the readme if someone can help me get it working.

**Comment by shortwavedave** [comment]
Also, how to do a non-ssl configuration  - it seems the ingress config requires secrets

**Comment by drf** [comment]
Hi @shortwavedave , thanks for the information. A couple more question:

1. what version of the Operator are you using? I'm assuming it's latest 0.10 - can you please try by using 0.11.0-rc.0?
2. Can you please past the logs of the Housekeeping pod when it crashes?

About no-SSL configuration, currently it is possible only for the API but not for the broker - in that case, it would make sense to use a self-signed certificate of sorts.

**Comment by shortwavedave** [comment]
@drf Thanks for the reply. When I run  `astartectl cluster upgrade-operator` I get the following message:

> You're currently running Astarte Operator version 0.10.2, no updates are available.

What's the best way to upgrade to 0.11.0?

**Comment by shortwavedave** [comment]
nevermind - answered my own question with this command:

`astartectl cluster upgrade-operator --version 0.11.0-rc.0`

**Comment by shortwavedave** [comment]
So, I tried to deploy with operator 0.11.0-rc.0 astarte version 0.11.0-rc-0 and I get the following error:

> astartectl cluster instances deploy
> Using config file: /home/david/.astartectl.yaml
> What Astarte version would you like to install? [0.10.2] 0.11.0-rc.0
> Cluster has 1 nodes
> Allocatable CPU is 6000m
> Allocatable Memory is 7.7G
> 
> Unfortunately, your cluster allocatable resources do not allow for any profile to be deployed

What are the resources necessary to allow a profile to be deployed? It would be nice if this command would show the specific problem.

**Comment by shortwavedave** [comment]
I went ahead and used the default profile listed here [https://docs.astarte-platform.org/0.11/060-setup_cluster.html#using-a-standard-astarte-cr](Link) instead of using astartectl.

With this profile and the 0.11 operator the data-updater pod continually crashes with this error:

> kubectl logs -n astarte astarte-pigeo-data-updater-plant-84f796b6ff-n59h5
> ==> Generated sys.config in /app/var
> level=info ts=2020-03-11T15:45:58.570+00:00 msg="Starting application." module=Astarte.DataUpdaterPlant.Application function=start/2 tag=data_updater_plant_app_start
> level=info ts=2020-03-11T15:45:58.571+00:00 msg="AMQPDataConsumer supervisor init." module=Astarte.DataUpdaterPlant.ConsumersSupervisor function=init/1 tag=data_consumer_sup_init
> level=debug ts=2020-03-11T15:45:58.580+00:00 msg="Control connection for 172.17.0.8:9042 is up" module=Xandra.Cluster function=handle_cast/2
> level=debug ts=2020-03-11T15:45:58.581+00:00 msg="Started connection to {172, 17, 0, 8}" module=Xandra.Cluster function=start_pool/3
> level=debug ts=2020-03-11T15:45:58.581+00:00 msg="Discovered peers: []" module=Xandra.Cluster function=handle_cast/2
> level=warn ts=2020-03-11T15:45:58.584+00:00 msg="RabbitMQ Connection error: :unknown_host. Retrying connection in 10000 ms." module=Astarte.DataUpdaterPlant.AMQPDataConsumer.ConnectionManager function=disconnected/3 tag=data_consumer_conn_err
> level=warn ts=2020-03-11T15:45:58.590+00:00 msg="RabbitMQ Connection error: :unknown_host" module=Astarte.DataUpdaterPlant.AMQPEventsProducer function=rabbitmq_connect/1 tag=events_producer_conn_err
> level=info ts=2020-03-11T15:45:58.594+00:00 msg="Application astarte_data_updater_plant exited: Astarte.DataUpdaterPlant.Application.start(:normal, []) returned an error: shutdown: failed to start child: Astarte.DataUpdaterPlant.DataPipelineSupervisor\n    ** (EXIT) shutdown: failed to start child: Astarte.DataUpdaterPlant.AMQPEventsProducer\n        ** (EXIT) :connection_failed" module=application_controller function=info_exited/3
> {"Kernel pid terminated",application_controller,"{application_start_failure,astarte_data_updater_plant,{{shutdown,{failed_to_start_child,'Elixir.Astarte.DataUpdaterPlant.DataPipelineSupervisor',{shutdown,{failed_to_start_child,'Elixir.Astarte.DataUpdaterPlant.AMQPEventsProducer',connection_failed}}}},{'Elixir.Astarte.DataUpdaterPlant.Application',start,[normal,[]]}}}"}
> Kernel pid terminated (application_controller) ({application_start_failure,astarte_data_updater_plant,{{shutdown,{failed_to_start_child,'Elixir.Astarte.DataUpdaterPlant.DataPipelineSupervisor',{shutdo
> 
> Crash dump is being written to: erl_crash.dump...done

**Comment by shortwavedave** [comment]
This configuration appears to be stable so far. Maybe there was a mismatch between the default config and the minicube resources. I'll go back to testing the ingress and see if that works now.

```
apiVersion: api.astarte-platform.org/v1alpha1
kind: Astarte
metadata:
  annotations:
    astarte-platform.org/deployment-manager: astartectl
    astarte-platform.org/deployment-profile: burst
  name: astarte-pigeo
  namespace: astarte
spec:
  api:
    host: pigeo.inno172.com/astarte-api
  cassandra:
    deploy: true
    heapNewSize: 256M
    maxHeapSize: 512M
    resources:
      limits:
        cpu: 1000m
        memory: 2048M
      requests:
        cpu: 500m
        memory: 1024M
    storage:
      size: 10Gi
  cfssl:
    deploy: true
    resources:
      limits:
        cpu: 0m
        memory: 128M
      requests:
        cpu: 0m
        memory: 128M
    storage:
      size: 2Gi
  components:
    resources:
      limits:
        cpu: 0m
        memory: 4096M
      requests:
        cpu: 0m
        memory: 2048M
  rabbitmq:
    deploy: true
    resources:
      limits:
        cpu: 1000m
        memory: 256M
      requests:
        cpu: 200m
        memory: 256M
    storage:
      size: 4Gi
  vernemq:
    deploy: true
    host: pigeo.inno172.com
    resources:
      limits:
        cpu: 1000m
        memory: 256M
      requests:
        cpu: 200m
        memory: 256M
    storage:
      size: 4Gi
  version: 0.11.0-rc.0
```
